services:
  db:
    image: mysql:8.3.0
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE:   knuckle
      MYSQL_USER:       appuser
      MYSQL_PASSWORD:   apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrate:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://appuser:apppassword@db:3306/knuckle
    ports:
      - "8000:8000"
    volumes:
      # 1) 프로젝트 전체 마운트
      - .:/app
      # 2) .venv 폴더만 익명 볼륨으로 덮어쓰기
      - /app/.venv
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
