version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_api
    ports:
      - "8000:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env