name: fix
description: 버그 수정 및 핫픽스 이슈 템플릿
title: "[FIX] "
labels: ["fix"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        버그 수정 및 핫픽스 요청 템플릿입니다.

  - type: input
    id: summary
    attributes:
      label: 요약
      description: 어떤 버그가 발생했는지 간단히 작성해주세요.
      placeholder: 예) 로그인 시 500 에러 발생
