name: CI

on:
  push:
    branches: ["#5/github-actions"]
  pull_request:
    branches: ["#5/github-actions"]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gitleaks v1 액션 사용
      - name: Run Gitleaks scan
        uses: zricethezav/gitleaks-action@v1
        with:
          scan_path: .          # 현재 디렉터리 전체 스캔
          redact: true          # 민감 정보 로그 마스킹
          fail_on_secrets: true # 시크릿 발견 시 CI 실패 처리
