name: CI

on:
  push:
    branches: [ "#5/github-actions" ]
  pull_request:
    branches: [ "#5/github-actions" ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      # 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gitleaks 설치
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v9.0.1/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks
          gitleaks version

      # Gitleaks 스캔
      - name: Run Gitleaks scan
        run: |
          gitleaks detect --source . --no-banner --verbose --redact
